[Fix] eslint.config.js
Convert to ES6 syntax to resolve > server@1.0.0 lint
> eslint './src/**/*.{ts,tsx,js,jsx}' --max-warnings=0
Oops! Something went wrong! :(
ESLint: 9.27.0
ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/jsgrades/jsgrades/server/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/jsgrades/jsgrades/server/eslint.config.js?mtime=1748027072940:5:18
    at ModuleJob.run (node:internal/modules/esm/module_job:263:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:540:24)
    at async dynamicImportConfig (/home/runner/work/jsgrades/jsgrades/server/node_modules/eslint/lib/config/config-loader.js:179:17)
    at async loadConfigFile (/home/runner/work/jsgrades/jsgrades/server/node_modules/eslint/lib/config/config-loader.js:269:9)
    at async ConfigLoader.calculateConfigArray (/home/runner/work/jsgrades/jsgrades/server/node_modules/eslint/lib/config/config-loader.js:578:23)
    at async #calculateConfigArray (/home/runner/work/jsgrades/jsgrades/server/node_modules/eslint/lib/config/config-loader.js:759:23)
    at async entryFilter (/home/runner/work/jsgrades/jsgrades/server/node_modules/eslint/lib/eslint/eslint-helpers.js:289:5)
    at async NodeHfs.<anonymous> (file:///home/runner/work/jsgrades/jsgrades/server/node_modules/@humanfs/core/src/hfs.js:574:24)
    at async NodeHfs.walk (file:///home/runner/work/jsgrades/jsgrades/server/node_modules/@humanfs/core/src/hfs.js:614:3)